spring:
  datasource:
    sherry:
      jdbcUrl: jdbc:mysql://127.0.0.1:13306/sherry?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456
      minIdle: 10
      maxPoolSize: 10
      driverClassName: com.mysql.cj.jdbc.Driver
