package cn.dhbin.isme.repository.sherry.entity;

import jakarta.annotation.Generated;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table permission
 */
public class Permission {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.id")
    private Integer id;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.name")
    private String name;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.code")
    private String code;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.type")
    private String type;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.parentId")
    private Integer parentid;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.path")
    private String path;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.redirect")
    private String redirect;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.icon")
    private String icon;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.component")
    private String component;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.layout")
    private String layout;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.keepAlive")
    private Byte keepalive;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.method")
    private String method;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.description")
    private String description;

    /**
     * Database Column Remarks:
     *   是否展示在页面菜单
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.show")
    private Byte show;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.enable")
    private Byte enable;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.order")
    private Integer order;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.id")
    public Integer getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.id")
    public void setId(Integer id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.name")
    public String getName() {
        return name;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.name")
    public void setName(String name) {
        this.name = name;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.code")
    public String getCode() {
        return code;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.code")
    public void setCode(String code) {
        this.code = code;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.type")
    public String getType() {
        return type;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.type")
    public void setType(String type) {
        this.type = type;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.parentId")
    public Integer getParentid() {
        return parentid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.parentId")
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.path")
    public String getPath() {
        return path;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.path")
    public void setPath(String path) {
        this.path = path;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.redirect")
    public String getRedirect() {
        return redirect;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.redirect")
    public void setRedirect(String redirect) {
        this.redirect = redirect;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.icon")
    public String getIcon() {
        return icon;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.icon")
    public void setIcon(String icon) {
        this.icon = icon;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.component")
    public String getComponent() {
        return component;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.component")
    public void setComponent(String component) {
        this.component = component;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.layout")
    public String getLayout() {
        return layout;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.layout")
    public void setLayout(String layout) {
        this.layout = layout;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.keepAlive")
    public Byte getKeepalive() {
        return keepalive;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.keepAlive")
    public void setKeepalive(Byte keepalive) {
        this.keepalive = keepalive;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.method")
    public String getMethod() {
        return method;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.method")
    public void setMethod(String method) {
        this.method = method;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.description")
    public String getDescription() {
        return description;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.description")
    public void setDescription(String description) {
        this.description = description;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.show")
    public Byte getShow() {
        return show;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.show")
    public void setShow(Byte show) {
        this.show = show;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.enable")
    public Byte getEnable() {
        return enable;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.enable")
    public void setEnable(Byte enable) {
        this.enable = enable;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.order")
    public Integer getOrder() {
        return order;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: permission.order")
    public void setOrder(Integer order) {
        this.order = order;
    }
}