package cn.dhbin.isme.repository.sherry.entity;

import jakarta.annotation.Generated;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table profile
 */
public class Profile {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: profile.id")
    private Integer id;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: profile.gender")
    private Integer gender;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: profile.avatar")
    private String avatar;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: profile.address")
    private String address;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: profile.email")
    private String email;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: profile.userId")
    private Integer userid;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: profile.nickName")
    private String nickname;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: profile.id")
    public Integer getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: profile.id")
    public void setId(Integer id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: profile.gender")
    public Integer getGender() {
        return gender;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: profile.gender")
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: profile.avatar")
    public String getAvatar() {
        return avatar;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: profile.avatar")
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: profile.address")
    public String getAddress() {
        return address;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: profile.address")
    public void setAddress(String address) {
        this.address = address;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: profile.email")
    public String getEmail() {
        return email;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: profile.email")
    public void setEmail(String email) {
        this.email = email;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: profile.userId")
    public Integer getUserid() {
        return userid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: profile.userId")
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: profile.nickName")
    public String getNickname() {
        return nickname;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: profile.nickName")
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }
}