package cn.dhbin.isme.repository.sherry.entity;

import jakarta.annotation.Generated;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table role_permissions_permission
 */
public class RolePermissionsPermission {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: role_permissions_permission.roleId")
    private Integer roleid;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: role_permissions_permission.permissionId")
    private Integer permissionid;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: role_permissions_permission.roleId")
    public Integer getRoleid() {
        return roleid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: role_permissions_permission.roleId")
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: role_permissions_permission.permissionId")
    public Integer getPermissionid() {
        return permissionid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: role_permissions_permission.permissionId")
    public void setPermissionid(Integer permissionid) {
        this.permissionid = permissionid;
    }
}