package cn.dhbin.isme.repository.sherry.entity;

import jakarta.annotation.Generated;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_roles_role
 */
public class UserRolesRole {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: user_roles_role.userId")
    private Integer userid;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: user_roles_role.roleId")
    private Integer roleid;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: user_roles_role.userId")
    public Integer getUserid() {
        return userid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: user_roles_role.userId")
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: user_roles_role.roleId")
    public Integer getRoleid() {
        return roleid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: user_roles_role.roleId")
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }
}