package cn.dhbin.isme.repository.sherry.entity;

import jakarta.annotation.Generated;
import java.time.LocalDateTime;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user
 */
public class User {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: user.id")
    private Integer id;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: user.username")
    private String username;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: user.password")
    private String password;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: user.enable")
    private Byte enable;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: user.createTime")
    private LocalDateTime createtime;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: user.updateTime")
    private LocalDateTime updatetime;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: user.id")
    public Integer getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: user.id")
    public void setId(Integer id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: user.username")
    public String getUsername() {
        return username;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: user.username")
    public void setUsername(String username) {
        this.username = username;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: user.password")
    public String getPassword() {
        return password;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: user.password")
    public void setPassword(String password) {
        this.password = password;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: user.enable")
    public Byte getEnable() {
        return enable;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: user.enable")
    public void setEnable(Byte enable) {
        this.enable = enable;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: user.createTime")
    public LocalDateTime getCreatetime() {
        return createtime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: user.createTime")
    public void setCreatetime(LocalDateTime createtime) {
        this.createtime = createtime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: user.updateTime")
    public LocalDateTime getUpdatetime() {
        return updatetime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: user.updateTime")
    public void setUpdatetime(LocalDateTime updatetime) {
        this.updatetime = updatetime;
    }
}